config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  # Api definition
  namespace :api, defaults: { format: :json },
  # constraints: { subdomain: 'api' },
  path: '/'  do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      resources :urls, only: [:show, :create]
    end
  end

  # You can have the root of your site routed with "root"
  root 'welcome#index'
end

app/models/url.rb
require 'uri'

class Url < ActiveRecord::Base
  has_one :url_content, dependent: :destroy

  validates :url, :guid, presence:true
  # validates_uniqueness_of :guid
  validate :url_validate

  def url_validate
    uri = URI.parse(url)
    errors.add(:url, 'is invalid') unless uri.kind_of?(URI::HTTP)
  rescue URI::InvalidURIError
    errors.add(:url, 'is invalid')
    false
  end

end

app/models/url_content.rb
class UrlContent < ActiveRecord::Base
  belongs_to :url
end

app/controllers/api/v1/urls_controller.rb
require 'current_app_load'
class Api::V1::UrlsController < ApplicationController
  respond_to :json

  def show
    url = Url.where(id: params[:id]).includes(:url_content).first
    current_load = CurrentAppLoad.new
    fresh_when(:etag => [url, current_load.server_load_code], :last_modified => url.updated_at.utc, :public => true) and return
    # render json: { "resource" => url, "poll-after" => current_load.poll_after, "server-load" => current_load.server_load_code }.to_json, status: 200
    render json: url, status: 200, location: [:api, url]
  end

  def create
    url = Url.new(url_params.merge(guid: SecureRandom.uuid))
    current_load = ::CurrentAppLoad.new
    if url.save
      ::PageSourcerJob.new.async.perform(url.id)
      render json: url, status: 201, location: [:api, url]
    else
      render json: { errors: url.errors }, status: 422
    end
  end

  private

  def url_params
    params.require(:url).permit(:url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'sourcer'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/api/v1/urls_helper.rb
module Api::V1::UrlsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PageSourcer</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/sourcer.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Page Sourcer" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
    <div class="lcentered-block">
      <a  href="/">
        <%= image_tag 'cpatil-logo.png', alt: 'cpatil.com', id: 'logo' %>
      </a>
    </div>
  </div>
</nav>

<%= yield %>

<%= javascript_include_tag "application" %>

<%= yield :javascript %>
</body>
</html>

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron centered-block">
    <h2>Page Sourcer</h2>

    <form class="form-inline" method="POST" id="new_url" action="<%= api_urls_path(format: :json) %>" accept-charset="UTF-8" data-remote="true">
      <div class="form-group width-100">
        <input type="url" class="first-input form-control centered-block" style="width: 100%" name="url" id="url" placeholder="http://yahoo.com" required pattern="https?://\w+.\w+.*">
      </div><br/><br/>
      <button type="submit" id="new_url_submit" class="btn btn-default">Sourcerize</button>
    </form>
  </div>
  <div id="spinner-wrapper" class="centered-block hidden">
    <canvas id="spinner" width="60" height="60"></canvas>
    <div id="spinner-message"></div>
  </div>
  <div id="panel-wrapper" class="hidden">
    <div id="result-panel" class="panel">
      <div class="panel-heading">
        <h3 class="panel-title">Result</h3>
      </div>
      <div class="panel-body"></div>
    </div>
  </div>
</div>